office/urls.py
from seahub.urls import *
from office.views import *
from django.conf.urls import url, patterns, include
from django.views.generic.base import TemplateView
from django.conf import settings
from office import admin


def i18n_javascript(request):
    return admin.site.i18n_javascript(request)

oa_patterns = [
    url(r'^$', home, name="officeHome"),
    url(r'^history/$', history, name="officeHistory"),
    # url(r'^page/(?:page-(?P<page>\d+)/)?$', index),
    url(r'^p/(?P<username>\S+)/$', user_index, name='user_index'),
    url(r'^distr/$', distribute_doc, {"distributed": True}, name="distribution"),
    url(r'^distred/$', distribute_doc, {"distributed": False}, name="distributed"),
    url(r'^todo/$', todo_doc, {"todo": True}, name="office_todo"),
    url(r'^done/$', todo_doc, {"todo": False}, name="office_done"),
    url(r'^doc/(?P<hashid>\w+)/$', document_page, name='office_page'),
    url(r'^search/$', search_doc, name='office_search'),
    url(r'^form/(?P<hashid>\w+)/$', print_form, name="print_form"),
    url(r'^loginjump', login_jump, name="office_jump"),
    # post
    url(r'^doc/(?P<hashid>\w+?)/assign$', distribution_document, name='office_assign'),
    url(r'^doc/(?P<hashid>\w+?)/commit$', commit_document, name='office_commit'),
    url(r'^commit/(?P<hashid>\w+?)/edit$', update_commit, name="edit_commit"),
    # ajax
    url(r'^ajax/upload_url$', get_upload_url),
    url(r'^ajax/delete_file$', delete_file),
    url(r'^ajax/issue', get_organization),
    # admin
    url(r'^admin/jsi18n', i18n_javascript),
    url(r'^admin/', include(admin.site.urls), name='officeAdmin'),
]

test_oa_patterns = [
    url(r'^meta$', display_meta, name='meta'),
    url(r'^test/$', test, name='test'),
    url(r'^index/$', TemplateView.as_view(template_name="office_index.html")),
    url(r'^paginator', test_paginator),
]

# fit: add django-debug-toolbar
if settings.DEBUG_EXT:
    import debug_toolbar
    urlpatterns += patterns(
        '',url(r'^__debug__/', include(debug_toolbar.urls)),
    )
    oa_patterns += test_oa_patterns

urlpatterns += patterns('', url(r'^oa/', include(oa_patterns)),)

office/models.py
# coding:utf-8
import os
from django.db import models
from django.db.models import F, Q
from django.db.models.signals import post_delete
from django.utils import timezone
from django.utils.html import format_html
from django.dispatch import receiver
from django.core.urlresolvers import reverse
from seaserv import seafile_api
from office.settings import HASHIDS
from office.utils import find_at


class BasisManager(models.Manager):
    pass
    # def update_or_create(self, defaults=None, **kwargs):
    #     """ New in Django 1.7
    #     :param defaults: fields what you update
    #     :param kwargs: fields what you create object
    #     :return: obj, [create: True | update: False]
    #     """
    #     defaults = defaults or {}
    #     try:
    #         obj = self.model.objects.get(**kwargs)
    #         for key, value in defaults.iteritems():
    #             setattr(obj, key, value)
    #         obj.save()
    #         return obj, True
    #     except self.model.DoesNotExist:
    #         defaults.update(kwargs)
    #         obj = self.model(**defaults)
    #         obj.save()
    #         return obj, False


# abstract Model
class TimeStampedModel(models.Model):
    """
    abstract base class, 提供创建时间和修改时间两个通用的field
    """
    created = models.DateTimeField(u'生成时间', auto_now_add=True)
    modified = models.DateTimeField(u'修改时间', auto_now=True)

    class Meta:
        abstract = True


class Tag(models.Model):
    name = models.CharField(max_length=32)


class DocumentManager(BasisManager):
    def user_distribute(self, username,commit):
        """
        :param commit: bool
        :return: query_set
        """
        return self.filter(
            distribution__uid = username,
            distribution__commit__isnull = commit
        )

    def user_todo(self, username,commit):
        """
        :param commit: bool
        :return: query_set
        """
        return self.filter(
            member__uid = username,
            member__commit__isnull = commit
        )

class Document(models.Model):
    STATE_CHOICES = (
        (0, u'紧急'),  # urgent
        (1, u'普通'),  # common
        (2, u'无关'),  # unrelated
    )
    reference = models.CharField(u'文号', max_length=32, unique=True, null=True, blank=True, default=None)
    title = models.CharField(u'文题', max_length=256)
    issue = models.CharField(u'发文单位', max_length=128)
    generated = models.DateField(u'成文时间', default=timezone.now)
    registered = models.DateField(u'登记时间', default=timezone.now)
    urgent = models.PositiveSmallIntegerField(u'状态', choices=STATE_CHOICES, default=1)
    note = models.TextField(u'备注', max_length=512, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    folder = models.CharField(max_length=128, null=True, blank=True, default=None)  # len 32 gen by gen_folder_name()
    repo_id = models.CharField(max_length=36, null=True, blank=True, default=None)  # len 36

    objects = DocumentManager()

    class Meta:
        verbose_name = u'文件'
        verbose_name_plural = u'文件'

    def __unicode__(self):
        # reference can be None
        return u'%s%s' % (u'%s：' % self.reference if self.reference else '', self.title)

    def commit_progress(self):
        """
        show commit progress
        :return: str "done/all"
        """
        done = self.member_set.filter(commit__isnull=False).count()
        count = self.member_set.count()
        if count == 0:
            return 0
        else:
            return '%s/%s' % (done, count)

    def delete(self, using=None):
        # print 'delete %s' %self
        seafile_api.del_file(self.repo_id, '', self.folder, 'Admin site')
        return super(Document, self).delete(using)

    def get_absolute_url(self):
        return reverse('office.views.document_page', args=[HASHIDS.encode(self.id)])

    def assigned(self):
        # return True
        return bool(self.distribution.commit_id)
    assigned.boolean = True
    assigned.short_description = u'办'
    assigned.admin_order_field = 'registered'

    def preview(self):
        """ use in list_display """
        url = self.get_absolute_url()
        # format UnicodeEncodeError
        # http://stackoverflow.com/questions/3235386/python-using-format-on-a-unicode-escaped-string
        return format_html(u'<a href="{0}" target="_blank">{1}</a>', url, u'打开')
    preview.short_description = u'浏览'
    preview.allow_tags = True  # avoid XSS should format_html()
    preview.admin_order_field = 'registered'

    def print_form_num(self):
        """ show in form for print page"""
        return int(Document.objects.filter(
            registered__year = self.registered.year,
            id__lt = self.id
        ).count()) + 1


class Attachment(models.Model):
    doc = models.ForeignKey(Document)
    file = models.CharField(max_length=1024, verbose_name=u'文件名', help_text='drop and drag')
    created = models.DateTimeField(u'生成时间', auto_now_add=True)

    def __unicode__(self):
        return self.file if len(unicode(self.file)) < 20 else os.path.basename(unicode(self.file))

    @property
    def repo(self):
        """ belong to the repo
        """
        return self.doc.repo_id

    @property
    def path(self):
        """ Root repo absolute path """
        return os.path.join(self.doc.folder, self.file)

    @property
    def file_obj(self):
        return seafile_api.get_dirent_by_path(self.repo, self.path)

    def get_absolute_url(self):
        return reverse('view_lib_file', args=[self.repo, '/%s' % self.path])
        # virtual repo
        # return reverse('view_lib_file', args=[self.repo, '/%s' % self.file])

    def delete(self, *args, **kwargs):
        seafile_api.del_file(self.repo, self.doc.folder, self.file, 'Django')
        return super(Attachment, self).delete(*args, **kwargs)


class Commit(TimeStampedModel):
    doc = models.ForeignKey(Document, verbose_name='document')
    uid = models.CharField(max_length=255)
    content = models.TextField(max_length=1024)

    objects = BasisManager()

    def __unicode__(self):
        return u"%s:%s" % (self.uid, self.doc_id)


class MemberManager(BasisManager):
    def users(self, docid):
        return self.values_list('uid', flat=True).filter(doc=docid)

    def users_set(self, docid):
        return set(self.users(docid))

    def user_add(self, doc_obj, uid):
        try:
            member = self.get(doc=doc_obj, uid=uid)
            member.count = F('count') + 1
            member.save()
        except Member.DoesNotExist:
            member = self.create(doc=doc_obj, uid=uid)
        return member

    def user_minus(self, doc_obj, uid):
        """
        remove the Member when the count is 1, else count minus 1
        """
        member = self.get(doc=doc_obj, uid=uid)
        if member.count <= 1:
            member.delete(with_commit=False)
        else:
            member.count = F('count') - 1
            member.save()
        return member

    def merge(self, doc_obj, new_members, old_members=set()):
        """
        :param doc_obj: "Document" instance
        :param new_members: type is set, new member
        :return:
        """
        for u in (new_members - old_members):
            self.user_add(doc_obj, u)
        for u in (old_members - new_members):
            self.user_minus(doc_obj, u)


class Member(TimeStampedModel):
    doc = models.ForeignKey(Document)
    uid = models.CharField(max_length=255)
    commit = models.OneToOneField(Commit, null=True, verbose_name='comment')
    count = models.IntegerField(default=1)

    objects = MemberManager()

    def __unicode__(self):
        return u"%s:%s" % (self.uid, self.doc_id)

    def get_absolute_url(self):
        return reverse('office.views.document_page', args=[int(self.doc_id)])

    def delete(self, using=None, with_commit=True):
        if self.commit:
            content = self.commit.content
            remove_set = find_at(content)
            Member.objects.merge(self.doc, set(), remove_set)
        if with_commit:
            self.commit.delete()
        super(Member, self).delete(using)


class Distribution(TimeStampedModel):
    doc = models.OneToOneField(Document)
    uid = models.CharField(max_length=255)
    commit = models.OneToOneField(Commit, null=True, verbose_name='comment')

    def __unicode__(self):
        return u"%s:%s" % (self.doc_id, self.uid)

    def get_absolute_url(self):
        return reverse('office.views.document_page', args=[int(self.doc_id)])


class Issue(models.Model):
    symbol = models.CharField(max_length=32, primary_key=True)
    organization = models.CharField(max_length=256)

    objects = BasisManager()


class InfoManager(BasisManager):
    def key2value(self, key):
        return self.values_list('value', flat=True).get(key=key)

    def value2key(self, value):
        return set(self.values_list('key', flat=True).filter(value=value))

    # def get_admins(self):
    #     kvs = self.filter(Q(key='root') | Q(key='admin'))
    #     return set([k.value for k in kvs])

    @property
    def root_repo(self):
        return self.key2value('root_repo')

    def get_download(self):
        return self.key2value('download')

    # @property
    # def root_user(self):  # todo: remove it
    #     return self.key2value('repo_user')


class Info(models.Model):
    key = models.CharField(max_length=32, primary_key=True)
    value = models.CharField(max_length=256)

    objects = InfoManager()

    class Meta:
        verbose_name = u'设置'
        verbose_name_plural = u'设置'

    def __unicode__(self):
        return u'%s' % self.key


class BlockHole(models.Model):
    # to save the folder name for upload files at admin site add view page
    # MySQL does not allow unique CharFields to have a max_length > 255
    folder = models.CharField(max_length=128, unique=True)

    def __unicode__(self):
        return self.folder

# abandon
# def del_root_repo_dirent(path):
#     """delete file from root repo

office/forms.py
from django.forms import ModelForm
from office.models import Commit, Document


class DocumentAdminForm(ModelForm):
    class Meta:
        model = Document
        #  https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/#selecting-the-fields-to-use
        fields = '__all__'  # for django 1.8

    def clean_reference(self):
        """ unique fields that allow null in admin interface
        http://stackoverflow.com/a/1400046/1265727
        """
        return self.cleaned_data['reference'] or None

    def clean_repo_id(self):
        return self.cleaned_data['repo_id'] or None


class CommitForm(ModelForm):
    class Meta:
        model = Commit
        # fields =('content',)
        fields = '__all__'

office/templates/distribute_doc.html
{% extends "doc_base.html" %}
{% load office_extras avatar_tags%}
{% block commit_form %}
    <div id="post_form" class="square opacity" >
        <strong>{{ user.nickname }}, 请回复： </strong>
        <div contenteditable="true" id="inputor" class="editable-inputor at-inputor"></div>
        {% url 'office_assign' doc.id|antispider as cu %}
        <form method="post" action="{{ cu }}" class="update-form" onsubmit="return copyContent(this)">
            {% csrf_token %}
            <p class="hide">
                <label for="commit">{{ user.username }}:</label>
                <textarea name="commit" id="commit"></textarea>
            </p>
            <input type="submit" value="提交" class="btn btn-success btn-full">
        </form>
    </div>
{% endblock commit_form %}

office/templates/doc_base.html
{% extends "office_base.html" %}
{% load staticfiles %}
{% load seahub_tags office_extras%}
{% block title %}文件:{{doc.title}}{% endblock title %}
{% block head_style %}
    <link href="{% static 'oa/atwho/jquery.atwho.css'%}" rel="stylesheet">
{% endblock head_style%}
{% block head_extra %}
    <script src="{% static 'oa/atwho/jquery.caret.js' %}"></script>
    <script src="{% static 'oa/atwho/jquery.atwho.js' %}"></script>
{% endblock head_extra %}
{% block content %}
    <div class="panel panel-default panel-padding container-fluids" style="margin-bottom: 10px;">
        <div class="panel-heading">
            <p class="panel-title clickselect">{{ doc }}</p>
        </div>
        <div class="panel-body">
            <a href="{% url 'print_form' doc.id|antispider %}" target="_blank">生成报告单</a>
            / <a href="{% url 'view_common_lib_dir' doc.repo_id doc.folder %}" target="_blank">打开文件目录</a>
            {% if user.is_officer %}
            / <a href="{% url 'admin:office_document_change' doc.id %}" target="_blank">打开管理页面 {{ doc.id }}</a>
            {% endif %}
        </div>
        <table class="table table-bordered">
            <thead><tr></tr></thead>
            <tbody>
            <tr>
                <td class="fieldset">
                    <dl>
                        <dt>文号:</dt>
                        <dd class="clickselect"><strong>{{ doc.reference|default:'-' }}</strong></dd>
                    </dl>
                </td>
                <td class="fieldset">
                    <dl>
                        <dt>成文时间:</dt>
                        <dd>{{ doc.generated|date:"Y年m月d日" }}</dd>
                    </dl>
                </td>
                <td class="fieldset">
                    <dl><dt>登记时间:</dt><dd>{{ doc.registered|date:"Y年m月d日" }}</dd></dl>
                </td>
            </tr>
            <tr>
                <td class="fieldset" colspan="3">
                    <dl>
                        <dt>文题:</dt>
                        <dd class="clickselect"><strong>{{ doc.title }}</strong></dd>
                    </dl>
                </td>
            </tr>
            <tr>
                <td class="fieldset" colspan="3">
                    <dl>
                        <dt>发文单位:</dt>
                        <dd class="clickselect"><strong>{{ doc.issue }}</strong></dd>
                    </dl>
                </td>
            </tr>
            {% if doc.note %}
                <tr>
                    <td class="fieldset" colspan="3">
                        <dl>
                            <dt>备注:</dt>
                            <dd>{{ doc.note }}</dd>
                        </dl>
                    </td>
                </tr>
            {% endif %}
            <tr>
                <td class="fieldset" colspan="3">
                    <dl>
                        <dt>文件:</dt>
                        <dd>
                            <ul class="list-unstyled">
                                {% for f in doc.attachment_set.all %}
                                    <li>
                                        <img src="{{ MEDIA_URL }}img/file/{{ f.file|file_icon_filter }}" alt="" />
                                        <a href="{% if user.is_anonymous %}{{ f.get_absolute_url|anonymousview }}{% else %}
                                        {{ f.get_absolute_url }}
                                        {% endif %}" target="_blank">{{ f.file }}</a>
                                    </li>
                                    {% empty %}
                                    <li><p>还未上传文件</p></li>
                                {% endfor %}
                            </ul>
                        </dd>
                    </dl>
                </td>
            </tr>
            <tr>
                <td class="fieldset" colspan="3">
                    <dl>
                        <dt>分配:</dt>
                        <dd>
                            {% for m in doc.member_set.all %}
                                <a class="label {% if m.commit %}label-success{% else %}label-default{% endif %}"
                                   href="{% url 'user_index' m.uid %}">{{ m.uid|email2nickname }}</a>
                            {% empty %}
                                <span>未分配</span>
                            {% endfor %}
                        </dd>
                    </dl>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="panel-footer">
            <nav>
                <ul class="pager">
                    {% if  pre_id != none %}
                        <li class="previous"><a href="{% url 'office_page' pre_id|antispider %}">前一个</a></li>
                    {% endif %}
                    {% if  next_id != none %}
                        <li class="next"><a href="{% url 'office_page' next_id|antispider %}">后一个</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    {% block commit_list %}{% endblock commit_list %}
    {% block commit_form %}{% endblock commit_form %}
{% endblock content %}
{% block foot_script %}
    <script type="text/javascript" src="{% static "oa/js/forms.js" %}"></script>
    <script type="text/javascript">
        $(function(){
            $(document).keydown(function(e) {
                var url = false;
                //console.log(e);
                if (e.which == 188 && e.altKey) {  // alt + <  to previous
                    {% if  pre_id != none %}url = "{% url 'office_page' pre_id|antispider %}";{% endif %}
                }
                else if (e.which == 190 && e.altKey) {  // alt + > to next
                    {% if  next_id != none %}url = "{% url 'office_page' next_id|antispider %}";{% endif %}
                }
                if (url) {
                    window.location = url;
                }
            });
        });
        $('.clickselect').click(function (e) {
            var sel = window.getSelection();
            var range = document.createRange();
            range.selectNode(this);
            sel.removeAllRanges();
            sel.addRange(range);
        });
    </script>
{% endblock foot_script %}

office/templates/doc_forms.html
{% load office_extras%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>多个打印</title>
    {#<link type="text/css" rel="stylesheet" href="css/print.css" media="print">#}
    <style>
        #printbutton{
            cursor: pointer;
            position: fixed;
            top:0; right:0;
            color: #ffffff; background-color: #002a80;
            padding: 7px;
        }
        .key{
            color: #555;
            text-decoration: none;
            text-align: center;
            margin: 3px;
            padding: 3px;
            background: #eff0f2;
            -moz-border-radius: 4px;
            border-radius: 4px;
            border-top: 1px solid #f5f5f5;
            -webkit-box-shadow:
                inset 0 0 25px #e8e8e8,
                0 1px 0 #c3c3c3,
                0 2px 0 #c9c9c9,
                0 2px 3px #333;
            -moz-box-shadow:
                inset 0 0 25px #e8e8e8,
                0 1px 0 #c3c3c3,
                0 2px 0 #c9c9c9,
                0 2px 3px #333;
            box-shadow:
                inset 0 0 25px #e8e8e8,
                0 1px 0 #c3c3c3,
                0 2px 0 #c9c9c9,
                0 2px 3px #333;
            text-shadow: 0px 1px 0px #f5f5f5;
        }
        /* 样式将只应用于打印 */
        @media print {
            #printbutton{
                display:none;
            }
        }
    </style>
</head>
<body>
<div id="printbutton">按 <span class="key">ctrl</span>+<span class="key"> p </span>键进行打印</div>
{% for id in ids %}
    <iframe name="iFrame{{ id }}" frameborder="0" scrolling="no" width="100%" src="{% url 'print_form' id|antispider %}" onload="this.height=iFrame{{ id }}.document.body.scrollHeight"></iframe>
    <div style="page-break-after:always;"></div>
{% endfor %}
<script>
    var pb = document.querySelector("#printbutton");
    pb.onclick = function () {
        window.print();
    }
</script>
</body>
</html>

office/templates/office_base.html
{#{% spaceless %}#}
{% load staticfiles %}
{% load seahub_tags avatar_tags office_extras%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="renderer" content="webkit">
    <link rel="icon" type="image/x-icon" href="/media/img/favicon.png"/>
    <title>{% block title %}{{ title }}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static "oa/bootstrap/css/bootstrap.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "oa/css/base.css" %}" />
    {% block head_style %}{% endblock head_style%}
    <script type="text/javascript" src="{% static "oa/js/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "oa/bootstrap/js/bootstrap.min.js" %}"></script>
    {% block head_script %}{% endblock head_script%}
    {% block head_extra %}{% endblock head_extra%}
</head>
<body class="my-background">
{% block navbar %}
    <nav class="my-navbar navbar navbar-default navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <i class="icon-bar"></i><i class="icon-bar"></i><i class="icon-bar"></i>
                </button>
                {# todo             <img src="" alt="Brand">#}
                <a href="{% url 'officeHome' %}" class="navbar-brand">Office</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav ">
                {% if user.is_officer %}
                    <li class="dropdown {% ifequal banner '分发文件' %}active{% endifequal %}">
                        <a href="#" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="glyphicon glyphicon-send" aria-hidden="true"></span> 分发文件<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{% url 'distribution' %}">未分发文件 {% distribute_count as dc %}
                                    {% if dc != 0 %}<span class="badge badge-unread pull-right">{{ dc }}</span>{% endif %}
                                </a>
                            </li>
                            <li><a href="{% url 'distributed' %}">已分发文件</a></li>
                        </ul>
                    </li>
                {% endif %}
                {% if not user.is_anonymous %}
                    <li class="{% ifequal banner '我的文件' %}active{% endifequal %} dropdown">
                        <a href="#" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> 我的文件<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{% url 'office_todo' %}">未完成文件 {% todo_count as tc %}
                                    {% if tc != 0 %}<span class="badge badge-unread pull-right">{{ tc }}</span>{% endif %}
                                </a>
                            </li>
                            <li><a href="{% url 'office_done' %}">已完成文件</a></li>
                        </ul>
                    </li>
                {% endif %}
                <li class="{% ifequal banner '文件历史' %}active{% endifequal %}">
                    <a href="{% url 'officeHistory' %}"><span class="glyphicon glyphicon-inbox" aria-hidden="true"></span> 文件历史</a>
                </li>
                <li class="{% ifequal banner '检索文件' %}active{% endifequal %}">
                    <a href="{% url 'office_search' %}"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> 检索文件</a>
                </li>
{#                <li>#}
{#                    <form class="navbar-form" role="search">#}
{#                        <div class="form-group">#}
{#                            <input type="text" class="form-control" placeholder="Search">#}
{#                        </div>#}
{#                        <button type="submit" class="btn btn-default">搜索</button>#}
{#                    </form>#}
{#                </li>#}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    {% if user.is_officer %}
                        <li><a href="{% url "admin:index" %}"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> 登记台</a></li>
                    {% endif %}
                    <li class="dropdown ">
                        <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" style="padding: 7px 15px;">{% avatar user.username 36 %}<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'user_profile' user.username %}" > 你好，{{ request.user.email|email2nickname }}</a></li>
                            <li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> 首页</a></li>
                            <li><a href="{% url 'auth_logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span> 退出</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'auth_login' %}?{{ REDIRECT_FIELD_NAME }}={{ request.path_info }}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> 请登录</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    </nav>
{% endblock navbar %}
<div id="content" class="container">
    {% block content %}
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="panel-padding">
                    <h3 class="panel-title my-panel-title {% block sign-css %}{% endblock %}">{% block panel %}我的文件{% endblock panel %}</h3>
                </div>
                <div class="panel-padding">
                    {% if document_page %}
                        <div class="my-list-group list-group">
                            {% for doc in document_page %}
                                <a href="{% url 'office.views.document_page' doc.id|antispider %}" class="list-group-item">
                                    <div class="row col-title">
                                        <div class="col-xs-9 col-sm-9 col-md-10"><span>{{ doc.title }}</span></div>
                                        <div class="col-xs-3 col-sm-3 col-md-2 text-right lighter">{{ doc.registered|date:"Y-m-d" }}</div>
                                    </div>
                                    <div class="row">
                                        <div class="col-xs-9 col-sm-9 col-md-10">
                                            <span class="label label-primary">{{ doc.issue }}</span>
                                            {% if doc.reference %}<span>{{ doc.reference }}</span>{% endif %}
                                        </div>
                                        <div class="col-xs-3 col-sm-3 col-md-2 text-right">
                                            {% if doc.attachment_set.count %}
                                                {{ doc.attachment_set.count }}个<span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>
                                            {% endif %}
                                            {% if doc.commit_progress %}
                                                <span class="badge">进度:{{ doc.commit_progress }}</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                </a>
                            {% endfor %}
                        </div>
                        {% block paginator %}
                            <nav>
                                <ul class="pager">
                                    {% if document_page.has_previous %}
                                        <li class="previous"><a href="?page={{ document_page.previous_page_number }}">&#60;&#60; 上一页</a></li>
                                    {% endif %}
                                    <li>{{ document_page.number }}/{{ document_page.paginator.num_pages }}</li>
                                    {% if document_page.has_next %}
                                        <li class="next"><a href="?page={{ document_page.next_page_number }}">下一页 &#62;&#62;</a></li>
                                    {% endif %}
                                </ul>
                            </nav>
                        {% endblock paginator %}
                    {% else %}
                        <p style="padding:7px" class="my-list-group">没有未完成文件</p>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endblock content %}
</div>
{%  block footer %}
<div id="footer">
    <div class="navbar navbar-fixed-bottom">
        <div class="container">
            <p class="text-right">MADE BY YOUR</p>
            <p class="text-right">Do have faith in what you're doing.</p>
        </div>
    </div>
</div>
{% endblock footer %}
{% block foot_script %}{% endblock foot_script %}
</body>
</html>
{#{% endspaceless %}#}

office/templates/office_distribution.html
{% extends "office_base.html" %}
{% block title %}分发文件{% endblock title %}
{% block panel %}
    {% if distributed %}未分发文件{% else %}已分发文件{% endif %}
{% endblock panel %}
{% block sign-css %}
    {% if distributed %}wait-block{% else %}sucess-block{% endif %}
{% endblock %}